### PR TITLE
fix: non-breaking implementation changes and proper tests (replaced invalid tests)

### LINKED ISSUE #55: fix issues with jest/no-conditional-expect
Search for the text: 
`eslint-disable-next-line jest/no-conditional-expect`

The disabling of these lines were temporary due to the eslint config upgrade. Using conditional expects do hide certain implementation issues or bad/incomplete tests.

## index.test.js

1. Get registration with retries -> Test for retries on 5xx response
2. Publish event with retries -> Test for retries on 5xx response
3. Fetch from journalling -> Fetch from journal with retries

## signatureUtils.test.js

1. Test Fetch Key from CloudFront with Invalid Pub Key Url -> verify for invalid pub key
2. Test Fetch Pem Encoded Public Keys -> verify for invalid pub key url throws
3. Test Get Key from Cache -> get key from cache throws

See #56, #57, and #58 before updating the tests.

### LINKED ISSUE #56: Incorrect implementation and test for function signatureUtils::fetchPublicKeyFromCloudFront
Function signatureUtils::fetchPublicKeyFromCloudFront:
https://github.com/adobe/aio-lib-events/blob/bfb5e17823a12f6c24cbe10d3fc532cb9451f8ff/src/signatureUtils.js#L147-L167

This is an odd use of both async/await and Promise.then, it works - but can be confusing for devs not used to it.

The then() clause assigns to a variable pubKey, which works in this case because of the await (if not pubKey would always be undefined), but it could just simply be the return value for the then(), and should therefore end up to be the return value of the await.

But the problematic item is the catch() clause. It returns `helpers.exportFunctions.genErrorResponse(500, error.message)`, which has two problems:
1. Since the return value of the await is not used, this return value will never be used.
2. `helpers.exportFunctions.genErrorResponse` returns an object, and this function explicitly says it should return a string in the jsdoc. This is a mismatch.

This therefore renders the test "Test Fetch Key from CloudFront with Invalid Pub Key Url -> verify for invalid pub key" in signatureUtils.test.js as an invalid test since it will never throw an error. In fact the test is bogus (it passes but it is made to pass) - it doesn't really test the (mocked) return value - it tests an error that it sets up itself.

The test is here: https://github.com/adobe/aio-lib-events/blob/bfb5e17823a12f6c24cbe10d3fc532cb9451f8ff/test/signatureUtils.test.js#L73-L90

### LINKED ISSUE #57: Incorrect implementation and test for function signatureUtils::fetchPemEncodedPublicKeys
Function signatureUtils::fetchPemEncodedPublicKeys :
https://github.com/adobe/aio-lib-events/blob/bfb5e17823a12f6c24cbe10d3fc532cb9451f8ff/src/signatureUtils.js#L50-L68

The problematic item is the catch() clause. It returns `helpers.exportFunctions.genErrorResponse(500, 'Error occurred while fetching pem encoded Public Key')`, which has a problem:
1. `helpers.exportFunctions.genErrorResponse` returns an object, and this function explicitly says it should return an Array of (two) strings (tuple).

This therefore renders the test "Test Fetch Pem Encoded Public Keys -> verify for invalid pub key url throws" in signatureUtils.test.js as an invalid test since it will never throw an error. In fact the test is bogus - it doesn't really test the (mocked) return value - it tests an error that it sets up itself.

The test is here: https://github.com/adobe/aio-lib-events/blob/bfb5e17823a12f6c24cbe10d3fc532cb9451f8ff/test/signatureUtils.test.js#L91-L108

### LINKED ISSUE #58: Invalid test for function signatureUtils::getKeyFromCache
Function signatureUtils::getKeyFromCache :
https://github.com/adobe/aio-lib-events/blob/bfb5e17823a12f6c24cbe10d3fc532cb9451f8ff/src/signatureUtils.js#L112-L134

On error, the function returns null, and never rethrows an Error.

The test "Test Get Key from Cache -> get key from cache throws" in signatureUtils.test.js is an invalid test since the tested function will never throw an error. In fact the test is bogus - it doesn't really test the return value or catch the function's error - it tests an error that it sets up itself.

The test is here: https://github.com/adobe/aio-lib-events/blob/bfb5e17823a12f6c24cbe10d3fc532cb9451f8ff/test/signatureUtils.test.js#L109-L121

### PR DESCRIPTION
**Pull request by shazron**
closes #55
closes #56
closes #57
closes #58

## How Has This Been Tested?

- npm test

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: src/signatureUtils.js [hunk 1]
```diff
@@ -62,7 +61,7 @@ async function fetchPemEncodedPublicKeys (pubKeyUrl1, pubKeyUrl2) {
     pubKey2Pem = await fetchPubKeyFromCacheOrApi(pubKeyUrl2, state)
   } catch (error) {
     logger.error('error occurred while fetching pem encoded public keys either from cache or public key urls due to %s', error.message)
-    return helpers.exportFunctions.genErrorResponse(500, 'Error occurred while fetching pem encoded Public Key')
```
Comment (shazron) [inline src/signatureUtils.js:65]: pre-empting questions on this, this line is effectively a no-op. See #57

**Review by moritzraho — APPROVED** [review]

File: src/signatureUtils.js [hunk 2]
```diff
@@ -152,18 +151,15 @@ async function getPubKeyFileName (pubKeyUrl) {
...
-  let pubKey
-  await fetch(publicKeyUrl)
-    .then(response => response.text())
-    .then(text => {
-      logger.info('successfully fetched the public key %s from cloud front url %s', text, publicKeyUrl)
-      pubKey = text
-    })
-    .catch(error => {
-      logger.error('error fetching the public key from cloud front url %s due to => %s', publicKeyUrl, error.message)
-      return helpers.exportFunctions.genErrorResponse(500, error.message)
```
Comment (shazron) [inline src/signatureUtils.js:164]: pre-empting questions on this, this line is effectively a no-op. See #56

**Review by MichaelGoberling — APPROVED** [review]
